/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData t_shirt = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData book = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData phonelink = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData toys = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData pan_tool = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData gift = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData free_breakfast = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData pets = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData wrench = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData event_seat = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData bicycle = const IconData(0xe80a, fontFamily: _kFontFam);
}
